namespace Turbo.Plugins
{

    public interface IAttributeList
    {

        IAttribute Axe_Bad_Data { get; }
        IAttribute Attribute_Timer { get; }
        IAttribute Attribute_Pool { get; }
        IAttribute Death_Count { get; }
        IAttribute DualWield_Hand { get; }
        IAttribute DualWield_Hand_Next { get; }
        IAttribute DualWield_Hands_Swapped { get; }
        IAttribute Respawn_Game_Time { get; }
        IAttribute Backpack_Slots { get; }
        IAttribute Shared_Stash_Slots { get; }
        IAttribute Strength { get; }
        IAttribute Dexterity { get; }
        IAttribute Intelligence { get; }
        IAttribute Vitality { get; }
        IAttribute Strength_Total { get; }
        IAttribute Dexterity_Total { get; }
        IAttribute Intelligence_Total { get; }
        IAttribute Vitality_Total { get; }
        IAttribute Strength_Bonus { get; }
        IAttribute Dexterity_Bonus { get; }
        IAttribute Intelligence_Bonus { get; }
        IAttribute Vitality_Bonus { get; }
        IAttribute Strength_Bonus_Percent { get; }
        IAttribute Dexterity_Bonus_Percent { get; }
        IAttribute Intelligence_Bonus_Percent { get; }
        IAttribute Vitality_Bonus_Percent { get; }
        IAttribute Strength_Reduction_Percent { get; }
        IAttribute Dexterity_Reduction_Percent { get; }
        IAttribute Intelligence_Reduction_Percent { get; }
        IAttribute Vitality_Reduction_Percent { get; }
        IAttribute Primary_Damage_Attribute { get; }
        IAttribute Armor { get; }
        IAttribute Armor_Bonus_Percent { get; }
        IAttribute Armor_Item { get; }
        IAttribute Armor_Bonus_Item { get; }
        IAttribute Armor_Item_Percent { get; }
        IAttribute Armor_Item_SubTotal { get; }
        IAttribute Armor_Item_Total { get; }
        IAttribute Armor_Total { get; }
        IAttribute Experience_Granted_Hi { get; }
        IAttribute Experience_Granted_Low { get; }
        IAttribute Experience_Next_Hi { get; }
        IAttribute Experience_Next_Lo { get; }
        IAttribute Alt_Experience_Next_Hi { get; }
        IAttribute Alt_Experience_Next_Lo { get; }
        IAttribute Rest_Experience_Hi { get; }
        IAttribute Rest_Experience_Lo { get; }
        IAttribute Rest_Experience_Bonus_Percent { get; }
        IAttribute Gold_Granted { get; }
        IAttribute Gold { get; }
        IAttribute Gold_Find { get; }
        IAttribute Gold_Find_Uncapped { get; }
        IAttribute Gold_Find_Handicap { get; }
        IAttribute Gold_Find_Alt_Levels_Total { get; }
        IAttribute Gold_Find_Community_Buff { get; }
        IAttribute Gold_Find_Potion_Buff { get; }
        IAttribute Gold_Find_Total { get; }
        IAttribute Level { get; }
        IAttribute Level_Cap { get; }
        IAttribute Alt_Level { get; }
        IAttribute Magic_Find { get; }
        IAttribute Magic_Find_Uncapped { get; }
        IAttribute Magic_Find_Handicap { get; }
        IAttribute Magic_Find_Alt_Levels_Total { get; }
        IAttribute Magic_Find_Capped_Subtotal { get; }
        IAttribute Magic_Find_Total { get; }
        IAttribute Magic_And_Gold_Find_Suppressed { get; }
        IAttribute Treasure_Find { get; }
        IAttribute Legendary_Find_Community_Buff { get; }
        IAttribute Resource_Cost_Reduction_Amount { get; }
        IAttribute Resource_Cost_Reduction_Total { get; }
        IAttribute Resource_Set_Point_Bonus { get; }
        IAttribute Faster_Healing_Percent { get; }
        IAttribute Spending_Resource_Heals_Percent { get; }
        IAttribute Bonus_Healing_Received_Percent { get; }
        IAttribute Reduced_Healing_Received_Percent { get; }
        IAttribute Healing_Well_Restores_Resource { get; }
        IAttribute Experience_Bonus { get; }
        IAttribute Experience_Bonus_Percent { get; }
        IAttribute Experience_Bonus_Percent_Handicap { get; }
        IAttribute Experience_Bonus_Percent_Total { get; }
        IAttribute Experience_Bonus_No_Penalty { get; }
        IAttribute Health_Globe_Bonus_Chance { get; }
        IAttribute Health_Globe_Bonus_Mult_Chance { get; }
        IAttribute Powerup_Globe_Bonus_Chance { get; }
        IAttribute Powerup_Globe_Bonus_Mult_Chance { get; }
        IAttribute Health_Globe_Bonus_Health { get; }
        IAttribute Increased_Health_From_Globes_Percent { get; }
        IAttribute Increased_Health_From_Globes_Percent_Total { get; }
        IAttribute Bonus_Health_Percent_Per_Second_From_Globes { get; }
        IAttribute Bonus_Health_Percent_Per_Second_From_Globes_Total { get; }
        IAttribute Mana_Gained_From_Globes_Percent { get; }
        IAttribute Mana_Gained_From_Globes { get; }
        IAttribute Resistance { get; }
        IAttribute Resistance_Percent { get; }
        IAttribute Resistance_Total { get; }
        IAttribute Resistance_All { get; }
        IAttribute Resistance_Percent_All { get; }
        IAttribute Resistance_From_Intelligence { get; }
        IAttribute Class_Damage_Reduction_Percent { get; }
        IAttribute Skill { get; }
        IAttribute Skill_From_Item { get; }
        IAttribute Skill_Total { get; }
        IAttribute TeamID { get; }
        IAttribute Team_Override { get; }
        IAttribute Invulnerable { get; }
        IAttribute Loading { get; }
        IAttribute Loading_Player_ACD { get; }
        IAttribute Loading_Power_SNO { get; }
        IAttribute Loading_Anim_Tag { get; }
        IAttribute Loading_NewGame { get; }
        IAttribute Auto_Porting_To_Save_Point { get; }
        IAttribute No_Damage { get; }
        IAttribute No_AutoPickup { get; }
        IAttribute Light_Radius_Percent_Bonus { get; }
        IAttribute Hitpoints_Cur { get; }
        IAttribute Hitpoints_Factor_Level { get; }
        IAttribute Hitpoints_Factor_Vitality { get; }
        IAttribute Hitpoints_Total_From_Vitality { get; }
        IAttribute Hitpoints_Total_From_Level { get; }
        IAttribute Hitpoints_Granted { get; }
        IAttribute Hitpoints_Granted_Duration { get; }
        IAttribute Hitpoints_Max { get; }
        IAttribute Hitpoints_Max_Bonus { get; }
        IAttribute Hitpoints_Max_Total { get; }
        IAttribute Hitpoints_Percent { get; }
        IAttribute Hitpoints_Regen_Per_Second { get; }
        IAttribute Hitpoints_Regen_Per_Second_Bonus { get; }
        IAttribute Hitpoints_Regen_Per_Second_Bonus_From_Skills { get; }
        IAttribute Hitpoints_Regen_Bonus_Percent { get; }
        IAttribute Hitpoints_Regen_Per_Second_Subtotal { get; }
        IAttribute Hitpoints_Regen_Reduction_Percent { get; }
        IAttribute Hitpoints_Regen_Per_Second_Health_Globe { get; }
        IAttribute Hitpoints_Regen_Per_Second_Total { get; }
        IAttribute Hitpoints_Max_Percent_Bonus { get; }
        IAttribute Hitpoints_Max_Percent_Bonus_Item { get; }
        IAttribute Hitpoints_Max_Percent_Bonus_Multiplicative { get; }
        IAttribute Hitpoints_Healed_Target { get; }
        IAttribute Hitpoints_Frozen { get; }
        IAttribute Healing_Suppressed { get; }
        IAttribute DOT_Damage_Taken_Queued { get; }
        IAttribute DOT_Damage_Taken_Queued_Tick { get; }
        IAttribute DOT_Damage_Taken_Queued_Player { get; }
        IAttribute DOT_Damage_Taken_Queued_Player_Tick { get; }
        IAttribute Healing_Received_Queued { get; }
        IAttribute Healing_Received_Queued_Tick { get; }
        IAttribute Staggered_Damage_Fraction { get; }
        IAttribute Staggered_Damage_Duration { get; }
        IAttribute Resource_Type_Primary { get; }
        IAttribute Resource_Type_Secondary { get; }
        IAttribute Resource_Cur { get; }
        IAttribute Resource_Max { get; }
        IAttribute Resource_Max_Bonus { get; }
        IAttribute Resource_Max_Total { get; }
        IAttribute Resource_Factor_Level { get; }
        IAttribute Resource_Granted { get; }
        IAttribute Resource_Granted_Duration { get; }
        IAttribute Resource_Percent { get; }
        IAttribute Resource_Regen_Per_Second { get; }
        IAttribute Resource_Regen_Bonus_Percent { get; }
        IAttribute Resource_Regen_Total { get; }
        IAttribute Resource_Regen_Stop_Regen { get; }
        IAttribute Resource_Max_Percent_Bonus { get; }
        IAttribute Resource_Capacity_Used { get; }
        IAttribute Resource_Effective_Max { get; }
        IAttribute Resource_Regen_Percent_Per_Second { get; }
        IAttribute Resource_Degeneration_Stop_Point { get; }
        IAttribute Highest_Solo_Rift_Level { get; }
        IAttribute Highest_Unlocked_Rift_Level { get; }
        IAttribute Last_Rift_Started_Level { get; }
        IAttribute Highest_Hero_Solo_Rift_Level { get; }
        IAttribute Movement_Scalar { get; }
        IAttribute Walking_Rate { get; }
        IAttribute Running_Rate { get; }
        IAttribute Sprinting_Rate { get; }
        IAttribute Strafing_Rate { get; }
        IAttribute Walking_Rate_Total { get; }
        IAttribute Running_Rate_Total { get; }
        IAttribute Last_Running_Rate { get; }
        IAttribute Sprinting_Rate_Total { get; }
        IAttribute Strafing_Rate_Total { get; }
        IAttribute Movement_Bonus_Total { get; }
        IAttribute Movement_Scalar_Subtotal { get; }
        IAttribute Movement_Scalar_Capped_Total { get; }
        IAttribute Movement_Scalar_Uncapped_Bonus { get; }
        IAttribute Movement_Scalar_Total { get; }
        IAttribute Movement_Bonus_Run_Speed { get; }
        IAttribute Movement_Scalar_Cap { get; }
        IAttribute Casting_Speed { get; }
        IAttribute Casting_Speed_Bonus { get; }
        IAttribute Casting_Speed_Total { get; }
        IAttribute Always_Hits { get; }
        IAttribute Hit_Chance { get; }
        IAttribute Knockback_Attack_Scalar { get; }
        IAttribute Attacks_Per_Second_Item { get; }
        IAttribute Attacks_Per_Second_Item_Percent { get; }
        IAttribute Attacks_Per_Second_Item_Subtotal { get; }
        IAttribute Attacks_Per_Second_Item_Bonus { get; }
        IAttribute Attacks_Per_Second_Item_Total { get; }
        IAttribute Attacks_Per_Second { get; }
        IAttribute Attacks_Per_Second_Bonus { get; }
        IAttribute Attacks_Per_Second_Total { get; }
        IAttribute Attacks_Per_Second_Percent_Cap { get; }
        IAttribute Attacks_Per_Second_Percent { get; }
        IAttribute Attacks_Per_Second_Percent_Uncapped { get; }
        IAttribute Attacks_Per_Second_Percent_Reduction { get; }
        IAttribute Attacks_Per_Second_Percent_Subtotal { get; }
        IAttribute AI_Cooldown_Reduction_Percent { get; }
        IAttribute Power_Cooldown_Min_Time { get; }
        IAttribute Power_Cooldown_Reduction_Percent { get; }
        IAttribute Power_Cooldown_Reduction_Percent_All { get; }
        IAttribute Power_Cooldown_Reduction_Percent_All_Capped { get; }
        IAttribute Damage_Delta { get; }
        IAttribute Damage_Delta_Total { get; }
        IAttribute Damage_Min { get; }
        IAttribute Damage_Bonus_Min { get; }
        IAttribute Damage_Min_Total { get; }
        IAttribute Damage_Delta_Total_All { get; }
        IAttribute Damage_Min_Total_All { get; }
        IAttribute Damage_Average_Total_All { get; }
        IAttribute Damage_Min_Subtotal { get; }
        IAttribute Damage_Percent_All_From_Skills { get; }
        IAttribute Damage_Weapon_Delta { get; }
        IAttribute Damage_Weapon_Delta_SubTotal { get; }
        IAttribute Damage_Weapon_Max { get; }
        IAttribute Damage_Weapon_Max_Total { get; }
        IAttribute Damage_Weapon_Max_Total_All { get; }
        IAttribute Damage_Weapon_Delta_Total { get; }
        IAttribute Damage_Weapon_Delta_Total_All { get; }
        IAttribute Damage_Weapon_Bonus_Delta { get; }
        IAttribute Damage_Weapon_Bonus_Delta_X1 { get; }
        IAttribute Damage_Weapon_Min { get; }
        IAttribute Damage_Weapon_Min_Total { get; }
        IAttribute Damage_Weapon_Min_Total_All { get; }
        IAttribute Damage_Weapon_Average { get; }
        IAttribute Damage_Weapon_Average_Total { get; }
        IAttribute Damage_Weapon_Average_Total_All { get; }
        IAttribute Damage_Weapon_Bonus_Min { get; }
        IAttribute Damage_Weapon_Bonus_Min_X1 { get; }
        IAttribute Damage_Weapon_Bonus_Flat { get; }
        IAttribute Damage_Weapon_Percent_Bonus { get; }
        IAttribute Damage_Weapon_Percent_All { get; }
        IAttribute Damage_Weapon_Percent_Total { get; }
        IAttribute Damage_Type_Percent_Bonus { get; }
        IAttribute Damage_Dealt_Percent_Bonus { get; }
        IAttribute Damage_Percent_Bonus_Witchdoctor { get; }
        IAttribute Damage_Percent_Bonus_Wizard { get; }
        IAttribute Crit_Percent_Base { get; }
        IAttribute Crit_Percent_Bonus_Capped { get; }
        IAttribute Crit_Percent_Bonus_Uncapped { get; }
        IAttribute Crit_Percent_Bonus_Hide_From_DPS { get; }
        IAttribute Crit_Percent_Cap { get; }
        IAttribute Crit_Damage_Cap { get; }
        IAttribute Crit_Damage_Percent { get; }
        IAttribute Crit_Damage_Percent_Uncapped { get; }
        IAttribute Crit_Effect_Time { get; }
        IAttribute Pierce_Chance { get; }
        IAttribute Damage_Absorb_Percent { get; }
        IAttribute Damage_Reduction_Total { get; }
        IAttribute Damage_Reduction_Current { get; }
        IAttribute Damage_Reduction_Last_Tick { get; }
        IAttribute Block_Chance { get; }
        IAttribute Block_Chance_Sub_Total { get; }
        IAttribute Block_Chance_Bonus_Item { get; }
        IAttribute Block_Chance_Item { get; }
        IAttribute Block_Chance_Item_Total { get; }
        IAttribute Block_Chance_Uncapped_Bonus { get; }
        IAttribute Block_Chance_Capped_Total { get; }
        IAttribute Block_Amount { get; }
        IAttribute Block_Amount_Bonus_Percent { get; }
        IAttribute Block_Amount_Total_Min { get; }
        IAttribute Block_Amount_Total_Max { get; }
        IAttribute Block_Amount_Item_Min { get; }
        IAttribute Block_Amount_Item_Delta { get; }
        IAttribute Block_Amount_Item_Bonus { get; }
        IAttribute Dodge_Chance_Bonus { get; }
        IAttribute Dodge_Chance_Bonus_Melee { get; }
        IAttribute Dodge_Chance_Bonus_Ranged { get; }
        IAttribute Dodge_Chance_Bonus_Additive { get; }
        IAttribute Dodge_Chance_Bonus_Hide_From_Toughness { get; }
        IAttribute Cannot_Dodge { get; }
        IAttribute Get_Hit_Current { get; }
        IAttribute Get_Hit_Max_Base { get; }
        IAttribute Get_Hit_Max_Per_Level { get; }
        IAttribute Get_Hit_Max { get; }
        IAttribute Get_Hit_Recovery_Base { get; }
        IAttribute Get_Hit_Recovery_Per_Level { get; }
        IAttribute Get_Hit_Recovery { get; }
        IAttribute Get_Hit_Damage { get; }
        IAttribute Get_Hit_Damage_Scalar { get; }
        IAttribute Last_Damage_MainActor { get; }
        IAttribute Last_ACD_Attacked { get; }
        IAttribute Ignores_Critical_Hits { get; }
        IAttribute Immunity { get; }
        IAttribute Untargetable { get; }
        IAttribute Immobolize { get; }
        IAttribute Immune_To_Knockback { get; }
        IAttribute Power_Immobilize { get; }
        IAttribute Stun_Chance { get; }
        IAttribute Stun_Length { get; }
        IAttribute Stun_Recovery { get; }
        IAttribute Stun_Recovery_Speed { get; }
        IAttribute Stunned { get; }
        IAttribute Stun_Immune { get; }
        IAttribute Poison_Length_Reduction { get; }
        IAttribute Bleeding { get; }
        IAttribute Bleed_Duration { get; }
        IAttribute Chilled { get; }
        IAttribute Freeze_Length_Reduction { get; }
        IAttribute Freeze_Immune { get; }
        IAttribute Chill_Duration_Bonus_Percent { get; }
        IAttribute Freeze_Duration_Bonus_Percent { get; }
        IAttribute Stun_Duration_Bonus_Percent { get; }
        IAttribute Immobilize_Duration_Bonus_Percent { get; }
        IAttribute Fear_Duration_Bonus_Percent { get; }
        IAttribute Blind_Duration_Bonus_Percent { get; }
        IAttribute Charm_Duration_Bonus_Percent { get; }
        IAttribute Slow_Duration_Bonus_Percent { get; }
        IAttribute Webbed { get; }
        IAttribute Slow { get; }
        IAttribute FireAura { get; }
        IAttribute LightningAura { get; }
        IAttribute ColdAura { get; }
        IAttribute PoisonAura { get; }
        IAttribute Blind { get; }
        IAttribute Enraged { get; }
        IAttribute Slowdown_Immune { get; }
        IAttribute Gethit_Immune { get; }
        IAttribute AttackSpeed_Reduction_Immune { get; }
        IAttribute Suffocation_Per_Second { get; }
        IAttribute Suffocation_Unit_Value { get; }
        IAttribute Thorns_Percent { get; }
        IAttribute Thorns_Percent_All { get; }
        IAttribute Thorns_Percent_Total { get; }
        IAttribute Thorns_Fixed { get; }
        IAttribute Thorns_Fixed_Bonus_Percent { get; }
        IAttribute Thorns_Fixed_Total { get; }
        IAttribute Thorns_AOE_Radius { get; }
        IAttribute Thorns_Has_Damage_Type { get; }
        IAttribute On_First_Hit_Thorns_Percent { get; }
        IAttribute Steal_Health_Percent { get; }
        IAttribute Steal_Mana_Percent { get; }
        IAttribute Resource_On_Hit { get; }
        IAttribute Resource_On_Hit_Bonus_Pct { get; }
        IAttribute Resource_On_Hit_Bonus { get; }
        IAttribute Resource_On_Kill { get; }
        IAttribute Resource_On_Crit { get; }
        IAttribute Hitpoints_On_Hit { get; }
        IAttribute Hitpoints_On_Kill { get; }
        IAttribute Hitpoints_On_Kill_Reduction_Percent { get; }
        IAttribute Hitpoints_On_Kill_Total { get; }
        IAttribute Damage_To_Mana { get; }
        IAttribute Last_Proc_Time { get; }
        IAttribute Damage_Power_Delta { get; }
        IAttribute Damage_Power_Min { get; }
        IAttribute Rope_Overlay { get; }
        IAttribute General_Cooldown { get; }
        IAttribute Power_Cooldown { get; }
        IAttribute Power_Cooldown_Start { get; }
        IAttribute Proc_Cooldown { get; }
        IAttribute Emote_Cooldown { get; }
        IAttribute Projectile_Speed { get; }
        IAttribute Projectile_Speed_Increase_Percent { get; }
        IAttribute DestroyWhenPathBlocked { get; }
        IAttribute Skill_Toggled_State { get; }
        IAttribute Skill_Charges { get; }
        IAttribute Next_Charge_Gained_time { get; }
        IAttribute Recharge_Start_Time { get; }
        IAttribute Act { get; }
        IAttribute Difficulty { get; }
        IAttribute Last_Damage_Amount { get; }
        IAttribute In_Knockback { get; }
        IAttribute Amplify_Damage_Type_Percent { get; }
        IAttribute Amplify_Damage_Skill_Percent { get; }
        IAttribute Amplify_Damage_Percent { get; }
        IAttribute Durability_Cur { get; }
        IAttribute Durability_Max { get; }
        IAttribute Durability_Last_Damage { get; }
        IAttribute Item_Quality_Level { get; }
        IAttribute Item_Quality_Level_Identified { get; }
        IAttribute Item_Cost_Percent_Bonus { get; }
        IAttribute Item_Equipped { get; }
        IAttribute Ping { get; }
        IAttribute Requirement { get; }
        IAttribute Requirements_Ease_Percent { get; }
        IAttribute Requirement_When_Equipped { get; }
        IAttribute Sockets { get; }
        IAttribute Sockets_Filled { get; }
        IAttribute Stats_All_Bonus { get; }
        IAttribute Item_Bound_To_ACD { get; }
        IAttribute Item_Locked_To_ACD { get; }
        IAttribute Item_Binding_Level_Override { get; }
        IAttribute Item_LegendaryItem_Level_Override { get; }
        IAttribute Item_Targeted_Player_Class { get; }
        IAttribute Item_Targeted_Hireling_Class { get; }
        IAttribute ItemStackQuantityHi { get; }
        IAttribute ItemStackQuantityLo { get; }
        IAttribute Run_Speed_Granted { get; }
        IAttribute Run_Speed_Duration { get; }
        IAttribute IdentifyCost { get; }
        IAttribute Seed { get; }
        IAttribute IsCrafted { get; }
        IAttribute IsVendorBought { get; }
        IAttribute DyeType { get; }
        IAttribute Loot_2_0_Drop { get; }
        IAttribute Post_2_1_2_Drop { get; }
        IAttribute Post_2_5_0_Drop { get; }
        IAttribute Ancient_Rank { get; }
        IAttribute Unidentified { get; }
        IAttribute RemoveLevelReq { get; }
        IAttribute ConsumableAddSockets { get; }
        IAttribute AddSocketsType_Weapon { get; }
        IAttribute AddSocketsType_Offhand { get; }
        IAttribute AddSocketsType_Legs { get; }
        IAttribute AddSocketsType_Chest { get; }
        IAttribute AddSocketsType_Helm { get; }
        IAttribute AddSocketsType_Jewelry { get; }
        IAttribute EnchantedAffixOld { get; }
        IAttribute EnchantedAffixNew { get; }
        IAttribute EnchantedAffixSeed { get; }
        IAttribute EnchantedAffixCount { get; }
        IAttribute TransmogGBID { get; }
        IAttribute TransmogGBIDTempOverride { get; }
        IAttribute HighlySalvageable { get; }
        IAttribute ItemUnlockTimeHi { get; }
        IAttribute ItemUnlockTimeLo { get; }
        IAttribute CubeEnchantedGemRank { get; }
        IAttribute CubeEnchantedGemType { get; }
        IAttribute Cube_Enchanted_Strength_Item { get; }
        IAttribute Cube_Enchanted_Dexterity_Item { get; }
        IAttribute Cube_Enchanted_Intelligence_Item { get; }
        IAttribute Cube_Enchanted_Vitality_Item { get; }
        IAttribute Always_Plays_GetHit { get; }
        IAttribute Hidden { get; }
        IAttribute Alpha_For_Other_Players { get; }
        IAttribute AlphaAttachments { get; }
        IAttribute RActor_Fade_Group { get; }
        IAttribute QuestRange { get; }
        IAttribute Attack_Cooldown_Min { get; }
        IAttribute Attack_Cooldown_Delta { get; }
        IAttribute InitialCooldownMinTotal { get; }
        IAttribute InitialCooldownDeltaTotal { get; }
        IAttribute Attack_Cooldown_Min_Total { get; }
        IAttribute Attack_Cooldown_Delta_Total { get; }
        IAttribute Closing_Cooldown_Min_Total { get; }
        IAttribute Closing_Cooldown_Delta_Total { get; }
        IAttribute Quest_Monster { get; }
        IAttribute Quest_MonsterEffect { get; }
        IAttribute Treasure_Class { get; }
        IAttribute Removes_Body_On_Death { get; }
        IAttribute InitialCooldownMin { get; }
        IAttribute InitialCooldownDelta { get; }
        IAttribute Knockback_Weight { get; }
        IAttribute UntargetableByPets { get; }
        IAttribute Damage_State_Current { get; }
        IAttribute Damage_State_Max { get; }
        IAttribute Is_Player_Decoy { get; }
        IAttribute Custom_Target_Weight { get; }
        IAttribute Gizmo_State { get; }
        IAttribute Gizmo_Charges { get; }
        IAttribute Chest_Open { get; }
        IAttribute Door_Locked { get; }
        IAttribute Door_Timer { get; }
        IAttribute Gizmo_Disabled_By_Script { get; }
        IAttribute Gizmo_Operator_ACDID { get; }
        IAttribute Triggering_Count { get; }
        IAttribute Gizmo_Operation_Radius_Override { get; }
        IAttribute Gate_Position { get; }
        IAttribute Gate_Velocity { get; }
        IAttribute Gizmo_Has_Been_Operated { get; }
        IAttribute Banner_Usable { get; }
        IAttribute Banner_Player_In_Combat { get; }
        IAttribute Pet_Owner { get; }
        IAttribute Pet_Creator { get; }
        IAttribute Pet_Type { get; }
        IAttribute DropsNoLoot { get; }
        IAttribute GrantsNoXP { get; }
        IAttribute Hireling_Class { get; }
        IAttribute Summoned_By_SNO { get; }
        IAttribute Pet_Proc_Scalar { get; }
        IAttribute Pet_Cannot_Be_Dismissed { get; }
        IAttribute Is_NPC { get; }
        IAttribute NPC_Is_Operatable { get; }
        IAttribute NPC_Is_Escorting { get; }
        IAttribute NPC_Has_Interact_Options { get; }
        IAttribute Conversation_Icon { get; }
        IAttribute Conversation_Icon_Override { get; }
        IAttribute Callout_Cooldown { get; }
        IAttribute Banter_Cooldown { get; }
        IAttribute Conversation_Heard_Count { get; }
        IAttribute Last_Tick_Shop_Entered { get; }
        IAttribute Is_Helper { get; }
        IAttribute Axe { get; }
        IAttribute Axe2H { get; }
        IAttribute ThrowingAxe { get; }
        IAttribute AxeAny { get; }
        IAttribute Bow { get; }
        IAttribute Crossbow { get; }
        IAttribute BowAny { get; }
        IAttribute Club { get; }
        IAttribute Club2H { get; }
        IAttribute ClubAny { get; }
        IAttribute Dagger { get; }
        IAttribute Mace { get; }
        IAttribute Mace2H { get; }
        IAttribute MaceAny { get; }
        IAttribute Sword { get; }
        IAttribute Sword2H { get; }
        IAttribute SwordAny { get; }
        IAttribute Polearm { get; }
        IAttribute Spear { get; }
        IAttribute Wand { get; }
        IAttribute ColdStaff { get; }
        IAttribute FireStaff { get; }
        IAttribute LightningStaff { get; }
        IAttribute PoisonStaff { get; }
        IAttribute StaffAny { get; }
        IAttribute Weapon1H { get; }
        IAttribute Weapon2H { get; }
        IAttribute WeaponMelee { get; }
        IAttribute WeaponRanged { get; }
        IAttribute Quiver { get; }
        IAttribute Reincarnation_Buff { get; }
        IAttribute Dead_Body_AnimTag { get; }
        IAttribute Spawned_by_ACDID { get; }
        IAttribute Summoned_By_ACDID { get; }
        IAttribute Summoner_ID { get; }
        IAttribute Banner_ACDID { get; }
        IAttribute Breakable_Shield_HP { get; }
        IAttribute Current_WeaponClass { get; }
        IAttribute Weapons_Sheathed { get; }
        IAttribute Held_In_OffHand { get; }
        IAttribute Attacks_Per_Second_Item_MainHand { get; }
        IAttribute Attacks_Per_Second_Item_OffHand { get; }
        IAttribute Attacks_Per_Second_Item_Total_MainHand { get; }
        IAttribute Attacks_Per_Second_Item_Total_OffHand { get; }
        IAttribute Damage_Weapon_Min_Total_MainHand { get; }
        IAttribute Damage_Weapon_Min_Total_OffHand { get; }
        IAttribute Damage_Weapon_Delta_Total_MainHand { get; }
        IAttribute Damage_Weapon_Delta_Total_OffHand { get; }
        IAttribute Attacks_Per_Second_Item_CurrentHand { get; }
        IAttribute Damage_Weapon_Min_Total_CurrentHand { get; }
        IAttribute Damage_Weapon_Delta_Total_CurrentHand { get; }
        IAttribute Has_Special_Death_AnimTag { get; }
        IAttribute Death_Type_Override { get; }
        IAttribute In_Combat { get; }
        IAttribute In_Combat_Next_Tick_Check { get; }
        IAttribute In_Conversation { get; }
        IAttribute Last_Tick_Potion_Used { get; }
        IAttribute Potion_Dilution_Percent { get; }
        IAttribute Out_Of_Combat_Health_Regen_Percent { get; }
        IAttribute Out_Of_Combat_Mana_Regen_Percent { get; }
        IAttribute Potion_Dilution_Duration { get; }
        IAttribute Potion_Dilution_Scalar { get; }
        IAttribute Feared { get; }
        IAttribute Fear_Immune { get; }
        IAttribute Last_Damage_ACD { get; }
        IAttribute Attached_To_ACD { get; }
        IAttribute Attachment_ACD { get; }
        IAttribute Normal_Attack_Replacement_Power_SNO { get; }
        IAttribute Damage_Type_Override { get; }
        IAttribute Minion_Count_Bonus_Percent { get; }
        IAttribute Expensive_Proc_Count { get; }
        IAttribute Post_260A_Legendary_Gem_Cap { get; }
        IAttribute Pet_Dont_Kill_When_Entering_Rifts { get; }
        IAttribute Champion_Clone_Next_Tick { get; }
        IAttribute Champion_Clone_Time_Min_In_Seconds { get; }
        IAttribute Champion_Clone_Time_Delta_In_Seconds { get; }
        IAttribute Champion_Clone_Hitpoint_Bonus_Percent { get; }
        IAttribute Champion_Clone_Damage_Bonus_Percent { get; }
        IAttribute Champion_Ghostly_Next_Tick { get; }
        IAttribute Champion_Ghostly_Inactive_Time_Min_In_Seconds { get; }
        IAttribute Champion_Ghostly_Inactive_Time_Delta_In_Seconds { get; }
        IAttribute Champion_Ghostly_Active_Time_Min_In_Seconds { get; }
        IAttribute Champion_Ghostly_Active_Time_Delta_In_Seconds { get; }
        IAttribute Champion_Ghostly_Saved_Dodge_Chance { get; }
        IAttribute Champion_Ghostly { get; }
        IAttribute Base_Element { get; }
        IAttribute Projectile_Amount_Bonus_Percent { get; }
        IAttribute Projectile_Reflect_Chance { get; }
        IAttribute Projectile_Reflect_Forced_Target { get; }
        IAttribute Projectile_Reflect_Damage_Scalar { get; }
        IAttribute Projectile_Reflect_Has_Damage_Cap { get; }
        IAttribute Projectile_Reflect_Damage_Cap_Remaining { get; }
        IAttribute Attack_Fear_Chance { get; }
        IAttribute Attack_Fear_Time_Min { get; }
        IAttribute Attack_Fear_Time_Delta { get; }
        IAttribute Buff_Visual_Effect { get; }
        IAttribute Buff_Icon_Start_Tick0 { get; }
        IAttribute Buff_Icon_Start_Tick1 { get; }
        IAttribute Buff_Icon_Start_Tick2 { get; }
        IAttribute Buff_Icon_Start_Tick3 { get; }
        IAttribute Buff_Icon_Start_Tick4 { get; }
        IAttribute Buff_Icon_Start_Tick5 { get; }
        IAttribute Buff_Icon_Start_Tick6 { get; }
        IAttribute Buff_Icon_Start_Tick7 { get; }
        IAttribute Buff_Icon_Start_Tick8 { get; }
        IAttribute Buff_Icon_Start_Tick9 { get; }
        IAttribute Buff_Icon_Start_Tick10 { get; }
        IAttribute Buff_Icon_Start_Tick11 { get; }
        IAttribute Buff_Icon_Start_Tick12 { get; }
        IAttribute Buff_Icon_Start_Tick13 { get; }
        IAttribute Buff_Icon_Start_Tick14 { get; }
        IAttribute Buff_Icon_Start_Tick15 { get; }
        IAttribute Buff_Icon_Start_Tick16 { get; }
        IAttribute Buff_Icon_Start_Tick17 { get; }
        IAttribute Buff_Icon_Start_Tick18 { get; }
        IAttribute Buff_Icon_Start_Tick19 { get; }
        IAttribute Buff_Icon_Start_Tick20 { get; }
        IAttribute Buff_Icon_Start_Tick21 { get; }
        IAttribute Buff_Icon_Start_Tick22 { get; }
        IAttribute Buff_Icon_Start_Tick23 { get; }
        IAttribute Buff_Icon_Start_Tick24 { get; }
        IAttribute Buff_Icon_Start_Tick25 { get; }
        IAttribute Buff_Icon_Start_Tick26 { get; }
        IAttribute Buff_Icon_Start_Tick27 { get; }
        IAttribute Buff_Icon_Start_Tick28 { get; }
        IAttribute Buff_Icon_Start_Tick29 { get; }
        IAttribute Buff_Icon_Start_Tick30 { get; }
        IAttribute Buff_Icon_Start_Tick31 { get; }
        IAttribute Buff_Icon_End_Tick0 { get; }
        IAttribute Buff_Icon_End_Tick1 { get; }
        IAttribute Buff_Icon_End_Tick2 { get; }
        IAttribute Buff_Icon_End_Tick3 { get; }
        IAttribute Buff_Icon_End_Tick4 { get; }
        IAttribute Buff_Icon_End_Tick5 { get; }
        IAttribute Buff_Icon_End_Tick6 { get; }
        IAttribute Buff_Icon_End_Tick7 { get; }
        IAttribute Buff_Icon_End_Tick8 { get; }
        IAttribute Buff_Icon_End_Tick9 { get; }
        IAttribute Buff_Icon_End_Tick10 { get; }
        IAttribute Buff_Icon_End_Tick11 { get; }
        IAttribute Buff_Icon_End_Tick12 { get; }
        IAttribute Buff_Icon_End_Tick13 { get; }
        IAttribute Buff_Icon_End_Tick14 { get; }
        IAttribute Buff_Icon_End_Tick15 { get; }
        IAttribute Buff_Icon_End_Tick16 { get; }
        IAttribute Buff_Icon_End_Tick17 { get; }
        IAttribute Buff_Icon_End_Tick18 { get; }
        IAttribute Buff_Icon_End_Tick19 { get; }
        IAttribute Buff_Icon_End_Tick20 { get; }
        IAttribute Buff_Icon_End_Tick21 { get; }
        IAttribute Buff_Icon_End_Tick22 { get; }
        IAttribute Buff_Icon_End_Tick23 { get; }
        IAttribute Buff_Icon_End_Tick24 { get; }
        IAttribute Buff_Icon_End_Tick25 { get; }
        IAttribute Buff_Icon_End_Tick26 { get; }
        IAttribute Buff_Icon_End_Tick27 { get; }
        IAttribute Buff_Icon_End_Tick28 { get; }
        IAttribute Buff_Icon_End_Tick29 { get; }
        IAttribute Buff_Icon_End_Tick30 { get; }
        IAttribute Buff_Icon_End_Tick31 { get; }
        IAttribute Could_Have_Ragdolled { get; }
        IAttribute Ambient_Damage_Effect_Last_Time { get; }
        IAttribute Scale_Bonus { get; }
        IAttribute Scale_Bonus_Is_Immediate { get; }
        IAttribute Deleted_On_Server { get; }
        IAttribute Scripted_Fade_Time { get; }
        IAttribute Does_No_Damage { get; }
        IAttribute Does_Fake_Damage { get; }
        IAttribute SlowTime_Debuff { get; }
        IAttribute Blocks_Projectiles { get; }
        IAttribute Frozen { get; }
        IAttribute Freeze_Damage_Percent_Bonus { get; }
        IAttribute Shatter_Chance { get; }
        IAttribute DualWield_BothAttack_Chance { get; }
        IAttribute Summon_Expiration_Tick { get; }
        IAttribute Summon_Count { get; }
        IAttribute Uninterruptible { get; }
        IAttribute QueueDeath { get; }
        IAttribute CantStartDisplayedPowers { get; }
        IAttribute GizmosIgnoreCantStartDisplayedPowers { get; }
        IAttribute Wizard_Slowtime_Proxy_ACD { get; }
        IAttribute DPS { get; }
        IAttribute Resurrection_Power { get; }
        IAttribute Freeze_Damage { get; }
        IAttribute Freeze_Capacity { get; }
        IAttribute Thaw_Rate { get; }
        IAttribute Chilled_Dur_Bonus_Percent { get; }
        IAttribute DOT_DPS { get; }
        IAttribute DamageCap_Percent { get; }
        IAttribute Item_Time_Sold { get; }
        IAttribute Forced_Hireling_Power { get; }
        IAttribute IsRooted { get; }
        IAttribute RootTargetACD { get; }
        IAttribute RootAutoDecayPerSecond { get; }
        IAttribute RootUnitValue { get; }
        IAttribute RootTotalTicks { get; }
        IAttribute Hide_Affixes { get; }
        IAttribute Rune_A { get; }
        IAttribute Rune_B { get; }
        IAttribute Rune_C { get; }
        IAttribute Rune_D { get; }
        IAttribute Rune_E { get; }
        IAttribute Resistance_Stun { get; }
        IAttribute Resistance_Stun_Total { get; }
        IAttribute Resistance_Root { get; }
        IAttribute Resistance_Root_Total { get; }
        IAttribute Resistance_Freeze { get; }
        IAttribute Resistance_Freeze_Total { get; }
        IAttribute Resistance_StunRootFreeze { get; }
        IAttribute CrowdControl_Reduction { get; }
        IAttribute Displays_Team_Effect { get; }
        IAttribute Cannot_Be_Added_To_AI_Target_List { get; }
        IAttribute SkillKit { get; }
        IAttribute Immune_To_Charm { get; }
        IAttribute Immune_To_Blind { get; }
        IAttribute Damage_Shield { get; }
        IAttribute Damage_Shield_Amount { get; }
        IAttribute Guard_Object_ACDID { get; }
        IAttribute Follow_Target_ACDID { get; }
        IAttribute Follow_Target_Type { get; }
        IAttribute Forced_Enemy_ACDID { get; }
        IAttribute NPC_Talk_Target_ANN { get; }
        IAttribute NPC_Conv_Target_ANN { get; }
        IAttribute Script_Target_ACDID { get; }
        IAttribute Look_Target_Server_ANN { get; }
        IAttribute Look_Target_Broadcast_Intensity { get; }
        IAttribute Look_Target_Broadcast_Radius { get; }
        IAttribute Stealthed { get; }
        IAttribute GemQuality { get; }
        IAttribute Gem_Attributes_Multiplier { get; }
        IAttribute ItemBuffIcon { get; }
        IAttribute ScrollDuration { get; }
        IAttribute Gizmo_Actor_SNO_To_Spawn { get; }
        IAttribute Gizmo_Actor_To_Spawn_Scale { get; }
        IAttribute Death_Replacement_Power_SNO { get; }
        IAttribute Attachment_Handled_By_Client { get; }
        IAttribute AI_In_Special_State { get; }
        IAttribute AI_Used_Scripted_Spawn_Anim { get; }
        IAttribute AI_Spawned_By_Inactive_Marker { get; }
        IAttribute Headstone_Player_ANN { get; }
        IAttribute Resource_Cost_Reduction_Percent { get; }
        IAttribute Resource_Cost_Reduction_Percent_Total { get; }
        IAttribute Resource_Cost_Reduction_Percent_All { get; }
        IAttribute Damage_Type_Cost_Reduction_Percent { get; }
        IAttribute Resistance_Penetration { get; }
        IAttribute Resistance_Penetration_Total { get; }
        IAttribute Resistance_Penetration_All { get; }
        IAttribute Resistance_Penetration_Percent_All { get; }
        IAttribute Fury_Effect_Level { get; }
        IAttribute Health_Potion_Bonus_Heal_Percent { get; }
        IAttribute Health_Potion_Affects_Allies_Percent { get; }
        IAttribute Free_Cast { get; }
        IAttribute Free_Cast_All { get; }
        IAttribute Health_Cost_Discount { get; }
        IAttribute Health_Cost_Scalar { get; }
        IAttribute Frailty_Health_Threshold { get; }
        IAttribute Frailty_Next_Application_Tick { get; }
        IAttribute Movement_Scalar_Reduction_Percent { get; }
        IAttribute Movement_Scalar_Reduction_Resistance { get; }
        IAttribute Damage_Absorb_Percent_All { get; }
        IAttribute World_Seed { get; }
        IAttribute Kill_Count_Record { get; }
        IAttribute Object_Destruction_Record { get; }
        IAttribute Single_Attack_Record { get; }
        IAttribute Environment_Attack_Record { get; }
        IAttribute Nephalem_Glory_Duration_Record { get; }
        IAttribute Root_Immune { get; }
        IAttribute Monster_Play_Get_Hit_Bonus { get; }
        IAttribute Stored_Contact_Frame { get; }
        IAttribute Buff_Icon_Count0 { get; }
        IAttribute Buff_Icon_Count1 { get; }
        IAttribute Buff_Icon_Count2 { get; }
        IAttribute Buff_Icon_Count3 { get; }
        IAttribute Buff_Icon_Count4 { get; }
        IAttribute Buff_Icon_Count5 { get; }
        IAttribute Buff_Icon_Count6 { get; }
        IAttribute Buff_Icon_Count7 { get; }
        IAttribute Buff_Icon_Count8 { get; }
        IAttribute Buff_Icon_Count9 { get; }
        IAttribute Buff_Icon_Count10 { get; }
        IAttribute Buff_Icon_Count11 { get; }
        IAttribute Buff_Icon_Count12 { get; }
        IAttribute Buff_Icon_Count13 { get; }
        IAttribute Buff_Icon_Count14 { get; }
        IAttribute Buff_Icon_Count15 { get; }
        IAttribute Buff_Icon_Count16 { get; }
        IAttribute Buff_Icon_Count17 { get; }
        IAttribute Buff_Icon_Count18 { get; }
        IAttribute Buff_Icon_Count19 { get; }
        IAttribute Buff_Icon_Count20 { get; }
        IAttribute Buff_Icon_Count21 { get; }
        IAttribute Buff_Icon_Count22 { get; }
        IAttribute Buff_Icon_Count23 { get; }
        IAttribute Buff_Icon_Count24 { get; }
        IAttribute Buff_Icon_Count25 { get; }
        IAttribute Buff_Icon_Count26 { get; }
        IAttribute Buff_Icon_Count27 { get; }
        IAttribute Buff_Icon_Count28 { get; }
        IAttribute Buff_Icon_Count29 { get; }
        IAttribute Buff_Icon_Count30 { get; }
        IAttribute Buff_Icon_Count31 { get; }
        IAttribute Observer { get; }
        IAttribute Resurrect_As_Observer { get; }
        IAttribute Combo_Level { get; }
        IAttribute Combo_Time_Last_Move { get; }
        IAttribute Burrowed { get; }
        IAttribute Death_Replacement_Effect_Group_SNO { get; }
        IAttribute Checkpoint_Resurrection_Allowed_Game_Time { get; }
        IAttribute Checkpoint_Resurrection_Forced_Game_Time { get; }
        IAttribute Corpse_Resurrection_Allowed_Game_Time { get; }
        IAttribute Corpse_Resurrection_Charges { get; }
        IAttribute Corpse_Resurrection_Disabled { get; }
        IAttribute Controlling_TimedEvent_SNO { get; }
        IAttribute Casting_Speed_Percent { get; }
        IAttribute Using_Bossbar { get; }
        IAttribute Power_Buff_0_Visual_Effect { get; }
        IAttribute Power_Buff_1_Visual_Effect { get; }
        IAttribute Power_Buff_2_Visual_Effect { get; }
        IAttribute Power_Buff_3_Visual_Effect { get; }
        IAttribute Power_Buff_4_Visual_Effect { get; }
        IAttribute Power_Buff_5_Visual_Effect { get; }
        IAttribute Power_Buff_6_Visual_Effect { get; }
        IAttribute Power_Buff_7_Visual_Effect { get; }
        IAttribute Power_Buff_8_Visual_Effect { get; }
        IAttribute Power_Buff_9_Visual_Effect { get; }
        IAttribute Power_Buff_10_Visual_Effect { get; }
        IAttribute Power_Buff_11_Visual_Effect { get; }
        IAttribute Power_Buff_12_Visual_Effect { get; }
        IAttribute Power_Buff_13_Visual_Effect { get; }
        IAttribute Power_Buff_14_Visual_Effect { get; }
        IAttribute Power_Buff_15_Visual_Effect { get; }
        IAttribute Power_Buff_16_Visual_Effect { get; }
        IAttribute Power_Buff_17_Visual_Effect { get; }
        IAttribute Power_Buff_18_Visual_Effect { get; }
        IAttribute Power_Buff_19_Visual_Effect { get; }
        IAttribute Power_Buff_20_Visual_Effect { get; }
        IAttribute Power_Buff_21_Visual_Effect { get; }
        IAttribute Power_Buff_22_Visual_Effect { get; }
        IAttribute Power_Buff_23_Visual_Effect { get; }
        IAttribute Power_Buff_24_Visual_Effect { get; }
        IAttribute Power_Buff_25_Visual_Effect { get; }
        IAttribute Power_Buff_26_Visual_Effect { get; }
        IAttribute Power_Buff_27_Visual_Effect { get; }
        IAttribute Power_Buff_28_Visual_Effect { get; }
        IAttribute Power_Buff_29_Visual_Effect { get; }
        IAttribute Power_Buff_30_Visual_Effect { get; }
        IAttribute Power_Buff_31_Visual_Effect { get; }
        IAttribute StoreSNO { get; }
        IAttribute Busy { get; }
        IAttribute Afk { get; }
        IAttribute LorePlaying { get; }
        IAttribute LastActionTimestamp { get; }
        IAttribute PortalNextTime { get; }
        IAttribute Repair_Discount_Percent { get; }
        IAttribute Resource_Degeneration_Prevented { get; }
        IAttribute Operatable { get; }
        IAttribute Has_Look_Override { get; }
        IAttribute Spawner_Concurrent_Count_ID { get; }
        IAttribute Disabled { get; }
        IAttribute Skill_Override { get; }
        IAttribute Skill_Override_Active { get; }
        IAttribute Skill_Override_Ended { get; }
        IAttribute Skill_Override_Ended_Active { get; }
        IAttribute Is_Power_Proxy { get; }
        IAttribute Force_No_Death_Animation { get; }
        IAttribute Player_WeaponClass_Anim_Override { get; }
        IAttribute Operatable_Story_Gizmo { get; }
        IAttribute Power_Buff_0_Visual_Effect_None { get; }
        IAttribute Power_Buff_0_Visual_Effect_A { get; }
        IAttribute Power_Buff_0_Visual_Effect_B { get; }
        IAttribute Power_Buff_0_Visual_Effect_C { get; }
        IAttribute Power_Buff_0_Visual_Effect_D { get; }
        IAttribute Power_Buff_0_Visual_Effect_E { get; }
        IAttribute Power_Buff_1_Visual_Effect_None { get; }
        IAttribute Power_Buff_1_Visual_Effect_A { get; }
        IAttribute Power_Buff_1_Visual_Effect_B { get; }
        IAttribute Power_Buff_1_Visual_Effect_C { get; }
        IAttribute Power_Buff_1_Visual_Effect_D { get; }
        IAttribute Power_Buff_1_Visual_Effect_E { get; }
        IAttribute Power_Buff_2_Visual_Effect_None { get; }
        IAttribute Power_Buff_2_Visual_Effect_A { get; }
        IAttribute Power_Buff_2_Visual_Effect_B { get; }
        IAttribute Power_Buff_2_Visual_Effect_C { get; }
        IAttribute Power_Buff_2_Visual_Effect_D { get; }
        IAttribute Power_Buff_2_Visual_Effect_E { get; }
        IAttribute Power_Buff_3_Visual_Effect_None { get; }
        IAttribute Power_Buff_3_Visual_Effect_A { get; }
        IAttribute Power_Buff_3_Visual_Effect_B { get; }
        IAttribute Power_Buff_3_Visual_Effect_C { get; }
        IAttribute Power_Buff_3_Visual_Effect_D { get; }
        IAttribute Power_Buff_3_Visual_Effect_E { get; }
        IAttribute Power_Buff_4_Visual_Effect_None { get; }
        IAttribute Power_Buff_4_Visual_Effect_A { get; }
        IAttribute Power_Buff_4_Visual_Effect_B { get; }
        IAttribute Power_Buff_4_Visual_Effect_C { get; }
        IAttribute Power_Buff_4_Visual_Effect_D { get; }
        IAttribute Power_Buff_4_Visual_Effect_E { get; }
        IAttribute Power_Buff_5_Visual_Effect_None { get; }
        IAttribute Power_Buff_5_Visual_Effect_A { get; }
        IAttribute Power_Buff_5_Visual_Effect_B { get; }
        IAttribute Power_Buff_5_Visual_Effect_C { get; }
        IAttribute Power_Buff_5_Visual_Effect_D { get; }
        IAttribute Power_Buff_5_Visual_Effect_E { get; }
        IAttribute Power_Buff_6_Visual_Effect_None { get; }
        IAttribute Power_Buff_6_Visual_Effect_A { get; }
        IAttribute Power_Buff_6_Visual_Effect_B { get; }
        IAttribute Power_Buff_6_Visual_Effect_C { get; }
        IAttribute Power_Buff_6_Visual_Effect_D { get; }
        IAttribute Power_Buff_6_Visual_Effect_E { get; }
        IAttribute Power_Buff_7_Visual_Effect_None { get; }
        IAttribute Power_Buff_7_Visual_Effect_A { get; }
        IAttribute Power_Buff_7_Visual_Effect_B { get; }
        IAttribute Power_Buff_7_Visual_Effect_C { get; }
        IAttribute Power_Buff_7_Visual_Effect_D { get; }
        IAttribute Power_Buff_7_Visual_Effect_E { get; }
        IAttribute Power_Buff_8_Visual_Effect_None { get; }
        IAttribute Power_Buff_8_Visual_Effect_A { get; }
        IAttribute Power_Buff_8_Visual_Effect_B { get; }
        IAttribute Power_Buff_8_Visual_Effect_C { get; }
        IAttribute Power_Buff_8_Visual_Effect_D { get; }
        IAttribute Power_Buff_8_Visual_Effect_E { get; }
        IAttribute Power_Buff_9_Visual_Effect_None { get; }
        IAttribute Power_Buff_9_Visual_Effect_A { get; }
        IAttribute Power_Buff_9_Visual_Effect_B { get; }
        IAttribute Power_Buff_9_Visual_Effect_C { get; }
        IAttribute Power_Buff_9_Visual_Effect_D { get; }
        IAttribute Power_Buff_9_Visual_Effect_E { get; }
        IAttribute Power_Buff_10_Visual_Effect_None { get; }
        IAttribute Power_Buff_10_Visual_Effect_A { get; }
        IAttribute Power_Buff_10_Visual_Effect_B { get; }
        IAttribute Power_Buff_10_Visual_Effect_C { get; }
        IAttribute Power_Buff_10_Visual_Effect_D { get; }
        IAttribute Power_Buff_10_Visual_Effect_E { get; }
        IAttribute Power_Buff_11_Visual_Effect_None { get; }
        IAttribute Power_Buff_11_Visual_Effect_A { get; }
        IAttribute Power_Buff_11_Visual_Effect_B { get; }
        IAttribute Power_Buff_11_Visual_Effect_C { get; }
        IAttribute Power_Buff_11_Visual_Effect_D { get; }
        IAttribute Power_Buff_11_Visual_Effect_E { get; }
        IAttribute Power_Buff_12_Visual_Effect_None { get; }
        IAttribute Power_Buff_12_Visual_Effect_A { get; }
        IAttribute Power_Buff_12_Visual_Effect_B { get; }
        IAttribute Power_Buff_12_Visual_Effect_C { get; }
        IAttribute Power_Buff_12_Visual_Effect_D { get; }
        IAttribute Power_Buff_12_Visual_Effect_E { get; }
        IAttribute Power_Buff_13_Visual_Effect_None { get; }
        IAttribute Power_Buff_13_Visual_Effect_A { get; }
        IAttribute Power_Buff_13_Visual_Effect_B { get; }
        IAttribute Power_Buff_13_Visual_Effect_C { get; }
        IAttribute Power_Buff_13_Visual_Effect_D { get; }
        IAttribute Power_Buff_13_Visual_Effect_E { get; }
        IAttribute Power_Buff_14_Visual_Effect_None { get; }
        IAttribute Power_Buff_14_Visual_Effect_A { get; }
        IAttribute Power_Buff_14_Visual_Effect_B { get; }
        IAttribute Power_Buff_14_Visual_Effect_C { get; }
        IAttribute Power_Buff_14_Visual_Effect_D { get; }
        IAttribute Power_Buff_14_Visual_Effect_E { get; }
        IAttribute Power_Buff_15_Visual_Effect_None { get; }
        IAttribute Power_Buff_15_Visual_Effect_A { get; }
        IAttribute Power_Buff_15_Visual_Effect_B { get; }
        IAttribute Power_Buff_15_Visual_Effect_C { get; }
        IAttribute Power_Buff_15_Visual_Effect_D { get; }
        IAttribute Power_Buff_15_Visual_Effect_E { get; }
        IAttribute Power_Buff_16_Visual_Effect_None { get; }
        IAttribute Power_Buff_16_Visual_Effect_A { get; }
        IAttribute Power_Buff_16_Visual_Effect_B { get; }
        IAttribute Power_Buff_16_Visual_Effect_C { get; }
        IAttribute Power_Buff_16_Visual_Effect_D { get; }
        IAttribute Power_Buff_16_Visual_Effect_E { get; }
        IAttribute Power_Buff_17_Visual_Effect_None { get; }
        IAttribute Power_Buff_17_Visual_Effect_A { get; }
        IAttribute Power_Buff_17_Visual_Effect_B { get; }
        IAttribute Power_Buff_17_Visual_Effect_C { get; }
        IAttribute Power_Buff_17_Visual_Effect_D { get; }
        IAttribute Power_Buff_17_Visual_Effect_E { get; }
        IAttribute Power_Buff_18_Visual_Effect_None { get; }
        IAttribute Power_Buff_18_Visual_Effect_A { get; }
        IAttribute Power_Buff_18_Visual_Effect_B { get; }
        IAttribute Power_Buff_18_Visual_Effect_C { get; }
        IAttribute Power_Buff_18_Visual_Effect_D { get; }
        IAttribute Power_Buff_18_Visual_Effect_E { get; }
        IAttribute Power_Buff_19_Visual_Effect_None { get; }
        IAttribute Power_Buff_19_Visual_Effect_A { get; }
        IAttribute Power_Buff_19_Visual_Effect_B { get; }
        IAttribute Power_Buff_19_Visual_Effect_C { get; }
        IAttribute Power_Buff_19_Visual_Effect_D { get; }
        IAttribute Power_Buff_19_Visual_Effect_E { get; }
        IAttribute Power_Buff_20_Visual_Effect_None { get; }
        IAttribute Power_Buff_20_Visual_Effect_A { get; }
        IAttribute Power_Buff_20_Visual_Effect_B { get; }
        IAttribute Power_Buff_20_Visual_Effect_C { get; }
        IAttribute Power_Buff_20_Visual_Effect_D { get; }
        IAttribute Power_Buff_20_Visual_Effect_E { get; }
        IAttribute Power_Buff_21_Visual_Effect_None { get; }
        IAttribute Power_Buff_21_Visual_Effect_A { get; }
        IAttribute Power_Buff_21_Visual_Effect_B { get; }
        IAttribute Power_Buff_21_Visual_Effect_C { get; }
        IAttribute Power_Buff_21_Visual_Effect_D { get; }
        IAttribute Power_Buff_21_Visual_Effect_E { get; }
        IAttribute Power_Buff_22_Visual_Effect_None { get; }
        IAttribute Power_Buff_22_Visual_Effect_A { get; }
        IAttribute Power_Buff_22_Visual_Effect_B { get; }
        IAttribute Power_Buff_22_Visual_Effect_C { get; }
        IAttribute Power_Buff_22_Visual_Effect_D { get; }
        IAttribute Power_Buff_22_Visual_Effect_E { get; }
        IAttribute Power_Buff_23_Visual_Effect_None { get; }
        IAttribute Power_Buff_23_Visual_Effect_A { get; }
        IAttribute Power_Buff_23_Visual_Effect_B { get; }
        IAttribute Power_Buff_23_Visual_Effect_C { get; }
        IAttribute Power_Buff_23_Visual_Effect_D { get; }
        IAttribute Power_Buff_23_Visual_Effect_E { get; }
        IAttribute Power_Buff_24_Visual_Effect_None { get; }
        IAttribute Power_Buff_24_Visual_Effect_A { get; }
        IAttribute Power_Buff_24_Visual_Effect_B { get; }
        IAttribute Power_Buff_24_Visual_Effect_C { get; }
        IAttribute Power_Buff_24_Visual_Effect_D { get; }
        IAttribute Power_Buff_24_Visual_Effect_E { get; }
        IAttribute Power_Buff_25_Visual_Effect_None { get; }
        IAttribute Power_Buff_25_Visual_Effect_A { get; }
        IAttribute Power_Buff_25_Visual_Effect_B { get; }
        IAttribute Power_Buff_25_Visual_Effect_C { get; }
        IAttribute Power_Buff_25_Visual_Effect_D { get; }
        IAttribute Power_Buff_25_Visual_Effect_E { get; }
        IAttribute Power_Buff_26_Visual_Effect_None { get; }
        IAttribute Power_Buff_26_Visual_Effect_A { get; }
        IAttribute Power_Buff_26_Visual_Effect_B { get; }
        IAttribute Power_Buff_26_Visual_Effect_C { get; }
        IAttribute Power_Buff_26_Visual_Effect_D { get; }
        IAttribute Power_Buff_26_Visual_Effect_E { get; }
        IAttribute Power_Buff_27_Visual_Effect_None { get; }
        IAttribute Power_Buff_27_Visual_Effect_A { get; }
        IAttribute Power_Buff_27_Visual_Effect_B { get; }
        IAttribute Power_Buff_27_Visual_Effect_C { get; }
        IAttribute Power_Buff_27_Visual_Effect_D { get; }
        IAttribute Power_Buff_27_Visual_Effect_E { get; }
        IAttribute Power_Buff_28_Visual_Effect_None { get; }
        IAttribute Power_Buff_28_Visual_Effect_A { get; }
        IAttribute Power_Buff_28_Visual_Effect_B { get; }
        IAttribute Power_Buff_28_Visual_Effect_C { get; }
        IAttribute Power_Buff_28_Visual_Effect_D { get; }
        IAttribute Power_Buff_28_Visual_Effect_E { get; }
        IAttribute Power_Buff_29_Visual_Effect_None { get; }
        IAttribute Power_Buff_29_Visual_Effect_A { get; }
        IAttribute Power_Buff_29_Visual_Effect_B { get; }
        IAttribute Power_Buff_29_Visual_Effect_C { get; }
        IAttribute Power_Buff_29_Visual_Effect_D { get; }
        IAttribute Power_Buff_29_Visual_Effect_E { get; }
        IAttribute Power_Buff_30_Visual_Effect_None { get; }
        IAttribute Power_Buff_30_Visual_Effect_A { get; }
        IAttribute Power_Buff_30_Visual_Effect_B { get; }
        IAttribute Power_Buff_30_Visual_Effect_C { get; }
        IAttribute Power_Buff_30_Visual_Effect_D { get; }
        IAttribute Power_Buff_30_Visual_Effect_E { get; }
        IAttribute Power_Buff_31_Visual_Effect_None { get; }
        IAttribute Power_Buff_31_Visual_Effect_A { get; }
        IAttribute Power_Buff_31_Visual_Effect_B { get; }
        IAttribute Power_Buff_31_Visual_Effect_C { get; }
        IAttribute Power_Buff_31_Visual_Effect_D { get; }
        IAttribute Power_Buff_31_Visual_Effect_E { get; }
        IAttribute Walk_Passability_Power_SNO { get; }
        IAttribute Passability_Power_SNO { get; }
        IAttribute Flippy_ID { get; }
        IAttribute Summoning_Machine_Num_Casters { get; }
        IAttribute Summoning_Machine_Spawn_Count { get; }
        IAttribute Summoning_Machine_Next_Spawn_Ticks { get; }
        IAttribute Summoning_Machine_Spawn_Team { get; }
        IAttribute Screen_Attack_Radius_Constant { get; }
        IAttribute MaxDamage_Done_Reduction_Percent1 { get; }
        IAttribute Set_Item_Count { get; }
        IAttribute Set_Bonus_Count { get; }
        IAttribute Spawner_Countdown_Percent { get; }
        IAttribute Attack_Slow { get; }
        IAttribute Power_Disabled { get; }
        IAttribute Weapon_Effect_Override { get; }
        IAttribute Debuff_Duration_Reduction_Percent { get; }
        IAttribute Uses_PvP_Power_Tags { get; }
        IAttribute Trait { get; }
        IAttribute Last_ACD_Attacked_By { get; }
        IAttribute Gold_PickUp_Radius { get; }
        IAttribute ClientOnlyEffect { get; }
        IAttribute Power_Saved_Attribute { get; }
        IAttribute Resource_Gain_Bonus_Percent { get; }
        IAttribute Looping_Animation_Start_Time { get; }
        IAttribute Looping_Animation_End_Time { get; }
        IAttribute Looping_Animation_Suppress_Item_Tooltips { get; }
        IAttribute Heal_Effect_Last_Played_Tick { get; }
        IAttribute Resource_Effect_Last_Played_tick { get; }
        IAttribute Thorns_Effect_Last_Played_tick { get; }
        IAttribute PVP_Kills { get; }
        IAttribute PVP_Deaths { get; }
        IAttribute PVP_Assists { get; }
        IAttribute PVP_Progression_Points_Gained { get; }
        IAttribute PVP_Current_Kill_Streak { get; }
        IAttribute PVP_Current_Death_Streak { get; }
        IAttribute PVP_Longest_Kill_Streak { get; }
        IAttribute PVP_Longest_Death_Streak { get; }
        IAttribute Turn_Rate_Scalar { get; }
        IAttribute Turn_Accel_Scalar { get; }
        IAttribute Turn_Deccel_Scalar { get; }
        IAttribute No_Health_Drop { get; }
        IAttribute Leader { get; }
        IAttribute IsContentRestrictedActor { get; }
        IAttribute InBossEncounter { get; }
        IAttribute God { get; }
        IAttribute AllowSkillChanges { get; }
        IAttribute MinimapActive { get; }
        IAttribute MinimapIconOverride { get; }
        IAttribute MinimapDisableArrow { get; }
        IAttribute Last_Blocked_ACD { get; }
        IAttribute Last_Blocked_Time { get; }
        IAttribute DeactivateLure { get; }
        IAttribute Weapons_Hidden { get; }
        IAttribute Main_Hand_Weapon_Hidden { get; }
        IAttribute Off_Hand_Weapon_Hidden { get; }
        IAttribute Actor_Updates_Attributes_From_Owner { get; }
        IAttribute Taunt_Target_ACD { get; }
        IAttribute Charm_Source_ACD { get; }
        IAttribute UI_Only_Percent_Damage_Increase { get; }
        IAttribute Projectile_Effect_SNO { get; }
        IAttribute On_Hit_Fear_Proc_Chance { get; }
        IAttribute On_Hit_Stun_Proc_Chance { get; }
        IAttribute On_Hit_Blind_Proc_Chance { get; }
        IAttribute On_Hit_Freeze_Proc_Chance { get; }
        IAttribute On_Hit_Chill_Proc_Chance { get; }
        IAttribute On_Hit_Slow_Proc_Chance { get; }
        IAttribute On_Hit_Immobilize_Proc_Chance { get; }
        IAttribute On_Hit_Knockback_Proc_Chance { get; }
        IAttribute On_Hit_Bleed_Proc_Chance { get; }
        IAttribute On_Hit_Bleed_Proc_Damage_Base { get; }
        IAttribute On_Hit_Bleed_Proc_Damage_Delta { get; }
        IAttribute Damage_Percent_Reduction_From_Ranged { get; }
        IAttribute Damage_Percent_Reduction_From_Melee { get; }
        IAttribute Damage_Percent_Reduction_Turns_Into_Heal { get; }
        IAttribute Damage_Percent_Reduction_From_Elites { get; }
        IAttribute Damage_Percent_Reduction_From_Type { get; }
        IAttribute Damage_Percent_Bonus_Vs_Monster_Type { get; }
        IAttribute Damage_Percent_Bonus_Vs_Elites { get; }
        IAttribute Item_Manipulation_Timeout { get; }
        IAttribute Picked_Up_Time { get; }
        IAttribute UnequippedTime { get; }
        IAttribute Last_ACD_Killed_Time { get; }
        IAttribute CannotDieDuring { get; }
        IAttribute Weapon_On_Hit_Fear_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Stun_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Blind_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Freeze_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Chill_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Slow_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Immobilize_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Knockback_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Damage_Base { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Damage_Delta { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Chance { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Damage { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Duration { get; }
        IAttribute Weapon_On_Hit_Fear_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Fear_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Fear_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Stun_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Stun_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Stun_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Blind_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Blind_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Blind_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Freeze_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Freeze_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Freeze_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Chill_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Chill_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Chill_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Slow_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Slow_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Slow_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Immobilize_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Immobilize_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Immobilize_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Knockback_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Knockback_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Knockback_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Damage_Base_MainHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Damage_Base_OffHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Damage_Base_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Damage_Delta_MainHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Damage_Delta_OffHand { get; }
        IAttribute Weapon_On_Hit_Bleed_Proc_Damage_Delta_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Chance_MainHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Chance_OffHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Chance_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Damage_MainHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Damage_Base_OffHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Damage_Base_CurrentHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Duration_MainHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Duration_OffHand { get; }
        IAttribute Weapon_On_Hit_Percent_Bleed_Proc_Duration_CurrentHand { get; }
        IAttribute Power_Damage_Percent_Bonus { get; }
        IAttribute Power_Instance_Damage_Percent_Bonus { get; }
        IAttribute Power_Resource_Reduction { get; }
        IAttribute Power_Resource_Reduction_Percent { get; }
        IAttribute Power_Cooldown_Reduction { get; }
        IAttribute Power_Cooldown_Reduction_All { get; }
        IAttribute Power_Duration_Increase { get; }
        IAttribute Power_Crit_Percent_Bonus { get; }
        IAttribute Weapon_Crit_Chance { get; }
        IAttribute Weapon_Crit_Chance_MainHand { get; }
        IAttribute Weapon_Crit_Chance_OffHand { get; }
        IAttribute Weapon_Crit_Chance_CurrentHand { get; }
        IAttribute Strength_Item { get; }
        IAttribute Dexterity_Item { get; }
        IAttribute Intelligence_Item { get; }
        IAttribute Vitality_Item { get; }
        IAttribute Item_Level_Requirement_Reduction { get; }
        IAttribute Item_Level_Requirement_Override { get; }
        IAttribute Item_Durability_Percent_Bonus { get; }
        IAttribute Item_Indestructible { get; }
        IAttribute Player_All_Items_Indestructible { get; }
        IAttribute Core_Attributes_From_Item_Bonus_Multiplier { get; }
        IAttribute Waiting_To_Accept_Resurrection { get; }
        IAttribute Ghosted { get; }
        IAttribute Special_Inventory_Has_Sold { get; }
        IAttribute Special_Inventory_Index { get; }
        IAttribute Inventory_Reroll_Time { get; }
        IAttribute Perk_Buff_Poll_Next_Time { get; }
        IAttribute Limited_Duration_Item_Poll_Next_Time { get; }
        IAttribute Power_Channel_Lockout_Time { get; }
        IAttribute Power_Buff_0_Lockout_Time { get; }
        IAttribute Power_Buff_1_Lockout_Time { get; }
        IAttribute Power_Buff_2_Lockout_Time { get; }
        IAttribute Power_Buff_3_Lockout_Time { get; }
        IAttribute Power_Buff_4_Lockout_Time { get; }
        IAttribute Power_Buff_5_Lockout_Time { get; }
        IAttribute Power_Buff_6_Lockout_Time { get; }
        IAttribute Power_Buff_7_Lockout_Time { get; }
        IAttribute Power_Buff_8_Lockout_Time { get; }
        IAttribute Power_Buff_9_Lockout_Time { get; }
        IAttribute Power_Buff_10_Lockout_Time { get; }
        IAttribute Power_Buff_11_Lockout_Time { get; }
        IAttribute Power_Buff_12_Lockout_Time { get; }
        IAttribute Power_Buff_13_Lockout_Time { get; }
        IAttribute Power_Buff_14_Lockout_Time { get; }
        IAttribute Power_Buff_15_Lockout_Time { get; }
        IAttribute Power_Buff_16_Lockout_Time { get; }
        IAttribute Power_Buff_17_Lockout_Time { get; }
        IAttribute Power_Buff_18_Lockout_Time { get; }
        IAttribute Power_Buff_19_Lockout_Time { get; }
        IAttribute Power_Buff_20_Lockout_Time { get; }
        IAttribute Power_Buff_21_Lockout_Time { get; }
        IAttribute Power_Buff_22_Lockout_Time { get; }
        IAttribute Power_Buff_23_Lockout_Time { get; }
        IAttribute Power_Buff_24_Lockout_Time { get; }
        IAttribute Power_Buff_25_Lockout_Time { get; }
        IAttribute Power_Buff_26_Lockout_Time { get; }
        IAttribute Power_Buff_27_Lockout_Time { get; }
        IAttribute Power_Buff_28_Lockout_Time { get; }
        IAttribute Power_Buff_29_Lockout_Time { get; }
        IAttribute Power_Buff_30_Lockout_Time { get; }
        IAttribute Power_Buff_31_Lockout_Time { get; }
        IAttribute Known_By_Owner { get; }
        IAttribute Never_Deactivates { get; }
        IAttribute Account_Under_Review { get; }
        IAttribute Projectile_Detonate_Time { get; }
        IAttribute Projectile_Uncapped_Lifetime { get; }
        IAttribute PageOfFate_Item { get; }
        IAttribute Accolade_0 { get; }
        IAttribute Accolade_1 { get; }
        IAttribute Accolade_2 { get; }
        IAttribute Accolade_3 { get; }
        IAttribute Accolade_4 { get; }
        IAttribute Accolade_0_Value { get; }
        IAttribute Accolade_1_Value { get; }
        IAttribute Accolade_2_Value { get; }
        IAttribute Accolade_3_Value { get; }
        IAttribute Accolade_4_Value { get; }
        IAttribute PVP_Rank { get; }
        IAttribute PVP_Tokens { get; }
        IAttribute PVP_Experience_Next_Lo { get; }
        IAttribute PVP_Experience_Next_Hi { get; }
        IAttribute PVP_Gold_Gained_This_Game { get; }
        IAttribute PVP_PVP_Experience_Gained_This_Game_Lo { get; }
        IAttribute PVP_PVP_Experience_Gained_This_Game_Hi { get; }
        IAttribute PVP_Normal_Experience_Gained_This_Game_Lo { get; }
        IAttribute PVP_Normal_Experience_Gained_This_Game_Hi { get; }
        IAttribute PVP_Tokens_Gained_This_Game { get; }
        IAttribute PVP_Level_Equalizer_Level { get; }
        IAttribute Is_Temporary_Lure { get; }
        IAttribute Ignore_Lure { get; }
        IAttribute Effect_Owner_ANN { get; }
        IAttribute Elite_Engaged { get; }
        IAttribute Engaged_Rare_Time { get; }
        IAttribute Engaged_Goblin_Time { get; }
        IAttribute On_Death_Accolade_0 { get; }
        IAttribute On_Death_Accolade_0_Value { get; }
        IAttribute Item_Power_Passive { get; }
        IAttribute PVP_TeamDeathmatch_Games_Played { get; }
        IAttribute Last_Health_Drop_Interval { get; }
        IAttribute CrowdControl_Resistance { get; }
        IAttribute CrowdControl_Projected_End_Time { get; }
        IAttribute Last_Continuous_Knockback_Power_ID { get; }
        IAttribute Charmed { get; }
        IAttribute Taunted { get; }
        IAttribute Dueling { get; }
        IAttribute PVP_Player_Revealed_On_Map { get; }
        IAttribute Targeted_Legendary_Chance { get; }
        IAttribute Seasonal_Legendary_Chance { get; }
        IAttribute Received_Seasonal_Legendary { get; }
        IAttribute Has_Dropped_Special_loot { get; }
        IAttribute Scroll_Buff { get; }
        IAttribute Buff_Exclusive_Type_Active { get; }
        IAttribute In_Combat_With_Player { get; }
        IAttribute Actor_Forwards_Buffs { get; }
        IAttribute Item_Marked_As_Junk { get; }
        IAttribute Allow_2H_And_Shield { get; }
        IAttribute Class_Damage_Reduction_Percent_PVP { get; }
        IAttribute Paragon_Bonus { get; }
        IAttribute Paragon_Bonus_Points_Available { get; }
        IAttribute Dungeon_Finder_Progress_Percent { get; }
        IAttribute Item_Trade_Player_High { get; }
        IAttribute Item_Trade_Player_Low { get; }
        IAttribute Item_Trade_End_Time { get; }
        IAttribute Item_Trade_Timer_ID { get; }
        IAttribute Item_Is_BOE { get; }
        IAttribute Season { get; }
        IAttribute DamageDoneTotalTrackedHi { get; }
        IAttribute DamageDoneTotalTrackedLo { get; }
        IAttribute DamageDoneTrackingStartTick { get; }
        IAttribute PowerPersistsAcrossGames { get; }
        IAttribute Experience_Bonus_Percent_IGR_Buff { get; }
        IAttribute Experience_Bonus_Percent_Anniversary_Buff { get; }
        IAttribute Experience_Bonus_Percent_Community_Buff { get; }
        IAttribute Experience_Bonus_Percent_Potion_Buff { get; }
        IAttribute Experience_Bonus_Percent_Super_Scalar { get; }
        IAttribute Experience_Bonus_Percent_Super_Scalar_Total { get; }
        IAttribute AlwaysShowFloatingNumbers { get; }
        IAttribute Targeted_Rare_Chance { get; }
        IAttribute Supress_Thorns_Effect { get; }
        IAttribute Dynamic_Entrance_GUID { get; }
        IAttribute Bonus_Chance_To_Be_Crit_Hit { get; }
        IAttribute Bonus_Chance_To_Be_Crit_Hit_By_Actor { get; }
        IAttribute Bonus_Chance_To_Receive_Crushing_Blown { get; }
        IAttribute Force_Gripped { get; }
        IAttribute PowerBonusAttackRadius { get; }
        IAttribute Item_Store_Player_High { get; }
        IAttribute Item_Store_Player_Low { get; }
        IAttribute Power_Primary_Resource_Cost_Override { get; }
        IAttribute Power_Secondary_Resource_Cost_Override { get; }
        IAttribute Power_Channel_Cost_Override { get; }
        IAttribute Rune_A_Override { get; }
        IAttribute Rune_B_Override { get; }
        IAttribute Rune_C_Override { get; }
        IAttribute Rune_D_Override { get; }
        IAttribute Rune_E_Override { get; }
        IAttribute Elemental_Effect_Amplitude_Bonus { get; }
        IAttribute Elemental_Effect_Duration_Bonus { get; }
        IAttribute Elemental_Effect_Proc_Chance_Bonus { get; }
        IAttribute Splash_Damage_Effect_Percent { get; }
        IAttribute Crushing_Blow_Proc_Chance { get; }
        IAttribute Item_Equipped_But_Disabled { get; }
        IAttribute Item_Equipped_But_Disabled_Duplicate_Legendary { get; }
        IAttribute Attribute_Projectile_Pass_Through { get; }
        IAttribute Attribute_Set_Item_Discount { get; }
        IAttribute Negative_Health_Globe_Spawn_Chance { get; }
        IAttribute Override_Attached_Anim { get; }
        IAttribute Has_Infinite_Shrine_Buffs { get; }
        IAttribute Item_Legendary_Item_Base_Item { get; }
        IAttribute Targeted_Magic_Chance { get; }
        IAttribute Dont_Update_Camera_While_Attached { get; }
        IAttribute LinkedDynamicEntranceGUID { get; }
        IAttribute Boost_TC_Index { get; }
        IAttribute Boost_TC_NextTime { get; }
        IAttribute Potion_Bonus_Armor_Percent { get; }
        IAttribute Potion_Bonus_Resist_All { get; }
        IAttribute Potion_Bonus_Hitpoints_Granted { get; }
        IAttribute Potion_Bonus_Buff_Duration { get; }
        IAttribute Potion_Bonus_Life_On_Hit { get; }
        IAttribute Potion_Bonus_Life_On_Kill { get; }
        IAttribute Last_Special_Item_Time_High { get; }
        IAttribute Last_Special_Item_Time_Low { get; }
        IAttribute Item_Rest_Bonus_Pool { get; }
        IAttribute Item_Unlucky_Bonus_Secs { get; }
        IAttribute Item_Unlucky_Bonus_Allow { get; }
        IAttribute Avenger_Buildup_Secs { get; }
        IAttribute Bounty_Objective { get; }
        IAttribute Illusion { get; }
        IAttribute TornadoStraighten { get; }
        IAttribute Prevent_Evade_During { get; }
        IAttribute Damage_Bonus_From_Nephalem_Glory { get; }
        IAttribute Item_Player_Recipient { get; }
        IAttribute Heavens_Fury_Attacker { get; }
        IAttribute Item_Assigned_Hero_High { get; }
        IAttribute Item_Assigned_Hero_Low { get; }
        IAttribute Pierce_Charge { get; }
        IAttribute Upscaled_Level { get; }
        IAttribute Resurrected { get; }
        IAttribute Damage_SidekickMultiplier { get; }
        IAttribute Thorns_AOE_Radius_Next_Time { get; }
        IAttribute Movement_Destroys_Waller_Walls { get; }
        IAttribute Mail_Flag_Icon { get; }
        IAttribute Tiered_Loot_Run_Key_Level { get; }
        IAttribute In_Tiered_Loot_Run_Level { get; }
        IAttribute Is_Loot_Run_Boss { get; }
        IAttribute ForcedMove { get; }
        IAttribute Effective_Level { get; }
        IAttribute Jewel_Rank { get; }
        IAttribute Item_Console_Max_Level { get; }
        IAttribute Console_Promo_Item { get; }
        IAttribute Double_BloodShards { get; }
        IAttribute Double_BountyBags { get; }
        IAttribute Jewel_Upgrades_Used { get; }
        IAttribute Jewel_Upgrades_Max { get; }
        IAttribute Jewel_Upgrades_Bonus { get; }
        IAttribute Item_Ignores_Pickup_Radius_For_Pickup { get; }
        IAttribute Hunter { get; }
        IAttribute Participating_In_Tiered_Loot_Run { get; }
        IAttribute Tiered_Loot_Run_Reward_Choice_State { get; }
        IAttribute Tiered_Loot_Run_Reward_Receives_Key { get; }
        IAttribute CurrentCosmeticEffect { get; }
        IAttribute Bloodshard_Bonus_Percent_Potion_Buff { get; }
        IAttribute XP_Potion_Buff_Expiration { get; }
        IAttribute Gold_Find_Potion_Buff_Expiration { get; }
        IAttribute Bloodshard_Potion_Buff_Expiration { get; }
        IAttribute Current_Cosmetic_Pet { get; }
        IAttribute Cosmetic_Pet_Power { get; }
        IAttribute Cosmetic_Pet_Expiration { get; }
        IAttribute Cosmetic_Portrait_Frame { get; }
        IAttribute HQ_Hot_Cold_State { get; }
        IAttribute HQ_Cursed_Realm_Reagents_Collected { get; }
        IAttribute HQ_Cursed_Realm_Reagents_Dropped { get; }
        IAttribute Debug_Movement_Type { get; }
        IAttribute Tiered_Loot_Run_Death_Count { get; }
        IAttribute Tiered_Loot_Run_Corpse_Resurrection_Allowed_GameTime { get; }
        IAttribute Last_Posted_Achievement_Points { get; }
        IAttribute Cosmetic_Pet_Actor { get; }
        IAttribute Platinum_Cap_Remaining { get; }
        IAttribute Platinum_Cap_Last_Gain { get; }
        IAttribute Last_Boss_Kill_Time { get; }
        IAttribute Last_Bounty_Complete_Time { get; }
        IAttribute Last_Treasure_Goblin_Kill_Time { get; }
        IAttribute Stash_Tabs_Purchased_With_Gold { get; }
        IAttribute Stash_Tabs_Rewarded_By_Achievements { get; }
        IAttribute Skill_Button_Flash { get; }
        IAttribute Projectile_Det_Path_Reflect_Count { get; }
        IAttribute Last_Cosmetic_Pet { get; }
        IAttribute Platinum_Last_Significant_Kill { get; }
        IAttribute Power_Last_Attribute_Snapshot_Update_Time { get; }
        IAttribute Skill_Button_Active_Glow { get; }
        IAttribute Participating_In_Set_Dungeon { get; }
        IAttribute Multiplicative_Damage_Percent_Bonus { get; }
        IAttribute Multiplicative_Damage_Percent_Bonus_For_Skill { get; }
        IAttribute Multiplicative_Damage_Percent_Bonus_For_Player { get; }
        IAttribute In_Set_Dungeon_World { get; }
        IAttribute Multiplicative_Damage_Percent_Bonus_No_Pets { get; }
        IAttribute Multiplicative_Damage_Percent_Bonus_ochallengeAgainst_CC_Targets { get; }
        IAttribute Multiplicative_Damage_Percent_Bonus_Against_Slowed_Targets { get; }
        IAttribute Summoned_By_Autocast { get; }
        IAttribute Necromancer_Corpse_Spawn_Chance { get; }
        IAttribute Necromancer_Last_Corpse_Spawn_Check_Tick { get; }
        IAttribute Necromancer_Corpse_Owner_Player_High { get; }
        IAttribute Necromancer_Corpse_Owner_Player_Low { get; }
        IAttribute Necromancer_Corpse_Charges { get; }
        IAttribute Necromancer_Corpse_Source_Monster_SNO { get; }
        IAttribute Necromancer_Corpse_Free_Casting { get; }
        IAttribute Currencies_Discovered { get; }
        IAttribute In_Tiered_Challenge_Rift { get; }
        IAttribute Necromancer_Cursed { get; }
        IAttribute Necromancer_Curse_Count { get; }
        IAttribute Necromancer_Unique_Curse_Count { get; }
        IAttribute Eligible_For_Weekly_Challenge_Reward { get; }
        IAttribute Force_Remote_FX { get; }
        IAttribute Weekly_Challenge_Reward_Icon { get; }
        IAttribute Item_Was_Touched_By_Armory { get; }
        IAttribute Item_Was_Touched_By_Armory_Last_Game { get; }
    }

}
